on: pull_request
name: CI jobs
jobs:
  main:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: My workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Spell check
        id: spell-check
        run: |
          status=0
          echo "### :bulb: Spell check report" > spell_check_report.md
          uv run typos --format brief >> spell_check_report.md || status=$?
          exit 0

      - name: Save spell check report artifact
        uses: actions/upload-artifact@v4
        with:
          name: Spell check report
          path: spell_check_report.md
